### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [AlexandreRio/ytpdsl#1]
Hello YTP DSL team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the YTP DSL project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>
```

We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by AlexandreRio** [comment]
Hello and thanks for your interest in the project.

I'll be very happy to see YTP DSL appears in the community website considering it's a more toy project than a real use case.

Here is the information you asked for:

```html
<tr>
	<td><a href="https://github.com/AlexandreRio/ytpdsl/">YTP DSL</a></td>
	<td>YTP DSL is a language to guide random video editing. The main goal is to produce a fun result based on a video library, guidance on duration and various video filters.</td>
	<td>GPL-3</td>
	<td>Language, Tool</td>
	<td>Alexandre Rio</td>
</tr>
```

Thanks!

Alexandre

**Comment by miklossy** [comment]
Thank you @AlexandreRio !

**Comment by miklossy** [comment]
The `YTP DSL` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
